# Generated by Django 4.1.7 on 2025-04-13 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Событие")),
                (
                    "date",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                2025, "Ошибка, год не может быть больше текущего"
                            )
                        ],
                        verbose_name="Дата (год)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Историческое событие",
                "verbose_name_plural": "Исторические события",
                "ordering": ["date"],
            },
        ),
    ]
